backend:
  name: git-gateway
  branch: dev
media_folder: public/images
public_folder: /images
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - label: 'Sections'
            name: 'sections'
            widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Image', name: 'imageSrc', widget: 'image' }
      - label: 'About Us'
        name: 'about'
        file: 'content/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
      - label: 'FAQ'
        name: 'faq'
        file: 'content/faq.md'
        fields:
          - label: 'Trusted Seed Membership FAQ'
            name: 'membershipFAQ'
            widget: list
            fields:
              - { label: 'Question', name: 'question', widget: 'string' }
              - { label: 'Answer', name: 'answer', widget: 'markdown' }
